<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => false,
'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'list_options' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'localidad',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cables',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'spliters',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'ctos',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'puertos_cto',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'ctos_view',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'logo',
'menu',
'list_options' ),
'grid' => array( 'welcome_item',
'welcome_item5',
'welcome_item6',
'welcome_item3',
'welcome_item1',
'welcome_item2' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'list_options' => 'supertop',
'welcome_item' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item3' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'list_options' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'welcome_item' => array( 'welcome_item',
'welcome_item3',
'welcome_item5',
'welcome_item6',
'welcome_item1',
'welcome_item2' ),
'list_options' => array( 'list_options' ),
'lang_selector' => array( 'lang_selector' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'list_options' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c5' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item5',
'welcome_item6',
'welcome_item3',
'welcome_item1',
'welcome_item2' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'localidad',
'linkPage' => 'list',
'linkText' => array( 'table' => 'localidad',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'globe' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'ctos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'ctos',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'sitemap' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cables',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cables',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'signal' ),
'background' => '#9ACD32',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'spliters',
'linkPage' => 'list',
'linkText' => array( 'table' => 'spliters',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'th-list' ),
'background' => '#DAA520',
'linkType' => 0 ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'lang_selector' ) ),
'lang_selector' => array( 'type' => 'lang_selector' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'puertos_cto',
'linkPage' => 'list',
'linkText' => array( 'table' => 'puertos_cto',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Puertos Cto description',
'type' => 0 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'ctos_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'ctos_view',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'background' => '#1E90FF',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'welcomePageStay' => true );
		?>