<?php
			$optionsArray = array( 'welcome' => array( 'welcomePageSkip' => true,
'welcomeItems' => array( 'logo' => array( 'menutItem' => false ),
'menu' => array( 'menutItem' => false ),
'list_options' => array( 'menutItem' => false ),
'loginform_login' => array( 'menutItem' => false ),
'username_button' => array( 'menutItem' => false ),
'welcome_item' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'localidad',
'page' => 'list' ),
'welcome_item5' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'cables',
'page' => 'list' ),
'welcome_item6' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'spliters',
'page' => 'list' ),
'welcome_item3' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'ctos',
'page' => 'list' ),
'welcome_item1' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'puertos_cto',
'page' => 'list' ),
'welcome_item2' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Mapa_General',
'page' => 'list' ),
'welcome_item7' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Mapa_ctos',
'page' => 'list' ),
'welcome_item4' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Mapa Puertos Libres',
'page' => 'list' ),
'welcome_item8' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Mapa Ventas',
'page' => 'list' ),
'welcome_item9' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Puertos_Libres',
'page' => 'list' ),
'welcome_item10' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'usuarios',
'page' => 'list' ),
'welcome_item11' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Vista_Digitadores',
'page' => 'list' ),
'welcome_item12' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Ingresar_cliente',
'page' => 'list' ),
'welcome_item13' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'reporte_afectaciones',
'page' => 'list' ),
'welcome_item14' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'reporte_afectaciones_view',
'page' => 'list' ),
'welcome_item15' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'tarjeta_olt',
'page' => 'list' ),
'welcome_item16' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'puertos_olt',
'page' => 'list' ),
'welcome_item17' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Clientes_por_puerto',
'page' => 'list' ),
'welcome_item18' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Departamentos',
'page' => 'list' ),
'welcome_item19' => array( 'menutItem' => true,
'group' => false,
'linkType' => 0,
'items' => null,
'table' => 'Ciudades',
'page' => 'list' ) ) ),
'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'supertop' => array( 'logo',
'menu',
'list_options',
'loginform_login',
'username_button' ),
'grid' => array( 'welcome_item',
'welcome_item5',
'welcome_item6',
'welcome_item3',
'welcome_item1',
'welcome_item2',
'welcome_item7',
'welcome_item4',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'logo' => 'supertop',
'menu' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'welcome_item' => 'grid',
'welcome_item5' => 'grid',
'welcome_item6' => 'grid',
'welcome_item3' => 'grid',
'welcome_item1' => 'grid',
'welcome_item2' => 'grid',
'welcome_item7' => 'grid',
'welcome_item4' => 'grid',
'welcome_item8' => 'grid',
'welcome_item9' => 'grid',
'welcome_item10' => 'grid',
'welcome_item11' => 'grid',
'welcome_item12' => 'grid',
'welcome_item13' => 'grid',
'welcome_item14' => 'grid',
'welcome_item15' => 'grid',
'welcome_item16' => 'grid',
'welcome_item17' => 'grid',
'welcome_item18' => 'grid',
'welcome_item19' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'list_options' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'welcome_item' => array( 'welcome_item',
'welcome_item3',
'welcome_item5',
'welcome_item6',
'welcome_item1',
'welcome_item2',
'welcome_item4',
'welcome_item7',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19' ),
'list_options' => array( 'list_options' ),
'lang_selector' => array( 'lang_selector' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'adminarea_link' => array( 'adminarea_link' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'menu',
'type' => 'menu',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'empty-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'horizontal' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'menu-topbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'list_options',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'welcome',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c5' => array( 'model' => 'c1',
'items' => array( 'welcome_item',
'welcome_item5',
'welcome_item6',
'welcome_item3',
'welcome_item1',
'welcome_item2',
'welcome_item7',
'welcome_item4',
'welcome_item8',
'welcome_item9',
'welcome_item10',
'welcome_item11',
'welcome_item12',
'welcome_item13',
'welcome_item14',
'welcome_item15',
'welcome_item16',
'welcome_item17',
'welcome_item18',
'welcome_item19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'welcome_item' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'localidad',
'linkPage' => 'list',
'linkText' => array( 'table' => 'localidad',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'globe' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#EDCA00',
'linkType' => 0 ),
'welcome_item3' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'ctos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'ctos',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'sitemap' ),
'linkComments' => array( 'type' => 0,
'text' => '' ),
'background' => '#8FBC8B',
'linkType' => 0 ),
'welcome_item5' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'cables',
'linkPage' => 'list',
'linkText' => array( 'table' => 'cables',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'signal' ),
'background' => '#9ACD32',
'linkType' => 0 ),
'welcome_item6' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'spliters',
'linkPage' => 'list',
'linkText' => array( 'table' => 'spliters',
'type' => 6 ),
'linkIcon' => array( 'fa' => 'th-list' ),
'background' => '#DAA520',
'linkType' => 0 ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'lang_selector' ) ),
'lang_selector' => array( 'type' => 'lang_selector' ),
'welcome_item1' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'puertos_cto',
'linkPage' => 'list',
'linkText' => array( 'table' => 'puertos_cto',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'leaf' ),
'linkComments' => array( 'text' => 'Puertos Cto description',
'type' => 0 ),
'background' => '#6B8E23',
'linkType' => 0 ),
'welcome_item2' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Mapa_General',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Mapa_General',
'type' => 6 ),
'linkIcon' => array( 'glyph' => 'briefcase' ),
'background' => '#1E90FF',
'linkType' => 0 ),
'welcome_item4' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Mapa Puertos Libres',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Mapa Puertos Libres',
'type' => 6 ),
'background' => '#2F4F4F',
'linkType' => 0 ),
'welcome_item7' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Mapa_ctos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Mapa_ctos',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item8' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Mapa Ventas',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Mapa Ventas',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item9' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Puertos_Libres',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Puertos_Libres',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item10' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'usuarios',
'linkPage' => 'list',
'linkText' => array( 'table' => 'usuarios',
'type' => 6 ),
'background' => '#008B8B',
'linkType' => 0 ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'welcome_item11' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Vista_Digitadores',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Vista_Digitadores',
'type' => 6 ),
'background' => '#9ACD32',
'linkType' => 0 ),
'welcome_item12' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Ingresar_cliente',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Ingresar_cliente',
'type' => 6 ),
'background' => '#CFAE83',
'linkType' => 0 ),
'welcome_item13' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'reporte_afectaciones',
'linkPage' => 'list',
'linkText' => array( 'table' => 'reporte_afectaciones',
'type' => 6 ),
'background' => '#D2691E',
'linkType' => 0 ),
'welcome_item14' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'reporte_afectaciones_view',
'linkPage' => 'list',
'linkText' => array( 'table' => 'reporte_afectaciones_view',
'type' => 6 ),
'background' => '#DB7093',
'linkType' => 0 ),
'welcome_item15' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'tarjeta_olt',
'linkPage' => 'list',
'linkText' => array( 'table' => 'tarjeta_olt',
'type' => 6 ),
'background' => '#6DA5C8',
'linkType' => 0 ),
'welcome_item16' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'puertos_olt',
'linkPage' => 'list',
'linkText' => array( 'table' => 'puertos_olt',
'type' => 6 ),
'background' => '#E67349',
'linkType' => 0 ),
'welcome_item17' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Clientes_por_puerto',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Clientes_por_puerto',
'type' => 6 ),
'background' => '#DC143C',
'linkType' => 0 ),
'welcome_item18' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Departamentos',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Departamentos',
'type' => 6 ),
'background' => '#B22222',
'linkType' => 0 ),
'welcome_item19' => array( 'type' => 'welcome_item',
'linkUrl' => '',
'linkTable' => 'Ciudades',
'linkPage' => 'list',
'linkText' => array( 'table' => 'Ciudades',
'type' => 6 ),
'background' => '#1E90FF',
'linkType' => 0 ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'welcomePageStay' => false );
		?>