<?php
			$optionsArray = array( 'totals' => array( 'id_localidad' => array( 'totalsType' => '' ),
'Localidad' => array( 'totalsType' => '' ),
'Tipo_Olt' => array( 'totalsType' => '' ),
'Serial_Olt' => array( 'totalsType' => '' ),
'Tipo_Mikrotik' => array( 'totalsType' => '' ),
'Serial_Mikrotik' => array( 'totalsType' => '' ),
'Serial_Ont_Prueba' => array( 'totalsType' => '' ),
'Serial_Raspberry' => array( 'totalsType' => '' ),
'Serial_Camara' => array( 'totalsType' => '' ),
'Nombre_del_custodio' => array( 'totalsType' => '' ),
'Telefono_del_custodio' => array( 'totalsType' => '' ),
'Contrato_de_energia' => array( 'totalsType' => '' ),
'Latitud' => array( 'totalsType' => '' ),
'Longitud' => array( 'totalsType' => '' ),
'Mapa' => array( 'totalsType' => '' ),
'Direccion' => array( 'totalsType' => '' ),
'Observaciones' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Localidad',
'Tipo_Olt',
'Serial_Olt',
'Tipo_Mikrotik',
'Serial_Mikrotik',
'Serial_Ont_Prueba',
'Serial_Raspberry',
'Serial_Camara',
'Nombre_del_custodio',
'Telefono_del_custodio',
'Contrato_de_energia',
'Latitud',
'Longitud',
'Mapa',
'Direccion',
'Observaciones' ),
'exportFields' => array( 'Localidad',
'Tipo_Olt',
'Serial_Olt',
'Tipo_Mikrotik',
'Serial_Mikrotik',
'Serial_Ont_Prueba',
'Serial_Raspberry',
'Serial_Camara',
'Nombre_del_custodio',
'Telefono_del_custodio',
'Contrato_de_energia',
'Latitud',
'Longitud',
'Mapa',
'Direccion',
'Observaciones' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Localidad' => array( 'export_field1' ),
'Tipo_Olt' => array( 'export_field2' ),
'Serial_Olt' => array( 'export_field3' ),
'Tipo_Mikrotik' => array( 'export_field4' ),
'Serial_Mikrotik' => array( 'export_field5' ),
'Serial_Ont_Prueba' => array( 'export_field6' ),
'Serial_Raspberry' => array( 'export_field7' ),
'Serial_Camara' => array( 'export_field8' ),
'Nombre_del_custodio' => array( 'export_field9' ),
'Telefono_del_custodio' => array( 'export_field10' ),
'Contrato_de_energia' => array( 'export_field11' ),
'Latitud' => array( 'export_field12' ),
'Longitud' => array( 'export_field13' ),
'Mapa' => array( 'export_field14' ),
'Direccion' => array( 'export_field15' ),
'Observaciones' => array( 'export_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'Localidad',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Tipo_Olt',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Serial_Olt',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Tipo_Mikrotik',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Serial_Mikrotik',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Serial_Ont_Prueba',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Serial_Raspberry',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Serial_Camara',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Nombre_del_custodio',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Telefono_del_custodio',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Contrato_de_energia',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Latitud',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Longitud',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Mapa',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Direccion',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Observaciones',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>