<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => null,
'extUserIdField' => null,
'fullnameField' => 'Nombre',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Clave',
'table' => array( 'connId' => 'isp_eisa_at_localhost',
'table' => 'usuarios' ),
'userGroupField' => 'Nombre',
'usernameField' => 'Nombre',
'userpicField' => '' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'iaFn2pVxaRx0OvBMIij5',
'JWTSecret' => 'kMvsDKNeGc7oXnqQBYK3' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LcvBxcqAAAAABZpXtHDLkIPdVpTJFpxtIE7WLVo',
'secretKey' => '6LcvBxcqAAAAALEbAPalymbrl_QUF5Ri0R_Vd70j',
'passesCount' => 3 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => true,
'tables' => array( 'Mapa_General' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'cables' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'ctos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'isp_eisa1_users' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'localidad' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'numero_puertos' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'numeros_cto' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'numeros_de_cables' => array( 'mainOwnerIDField' => 'id_Cables',
'securityOption' => 0,
'userOwnerIDField' => 'ID' ),
'numeros_de_spliters' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'puertos_cto' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ),
'spliters' => array( 'mainOwnerIDField' => '',
'securityOption' => 0,
'userOwnerIDField' => '' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'ISP_EISA_2.0',
'loginDataSource' => 'usuarios',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'isp_eisa prueba de mapas',
'dpTableConnId' => 'isp_eisa_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'active' => true,
'code' => '00',
'emailField' => null,
'extUserIdField' => null,
'fullnameField' => 'Nombre',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Clave',
'table' => array( 'connId' => 'isp_eisa_at_localhost',
'table' => 'usuarios' ),
'userGroupField' => 'Nombre',
'usernameField' => 'Nombre',
'userpicField' => '' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array(  ) );
?>